/*
  Copyright 2012 by Sean Luke
  Licensed under the Academic Free License version 3.0
  See the file "LICENSE" for more information
*/


package ec.ssr.functions;

import ec.*;

/* 
 * VladERCA.java
 * 
 * Created: Wed Nov  3 18:26:37 1999
 * By: Sean Luke

 <p>This ERC appears all three the Vladislavleva function sets.  It is not a constant but rather a function of one parameter (n) with an internal constant (c) and returns n^c.  Note that the value of c is drawn from the fully-closed range [-5.0, 5.0].

 <p>E. Vladislavleva, G. Smits, and D. Den Hertog. Order of Nonlinearity as a Complexity Measure for Models Generated by Symbolic Regression via Pareto Genetic Programming. <i>IEEE Trans EC,</i> 13(2):333-349, 2009.
*/


/**
 * @author Sean Luke
 * @version 1.0 
 */

public class EnergyERC extends RegERC {
    public String name() { 
        return "EnergyERC"; 
    }

    public void resetNode(final EvolutionState state, final int thread) {
        value = state.random[thread].nextDouble(true, true) * 5.0;
    }
}



